real-estate-agency/Controllers/AdminController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using real_estate_agency.Infrastructure;
using Microsoft.AspNet.Identity.Owin;
using real_estate_agency.Models.ViewModels;
using System.Threading.Tasks;
using real_estate_agency.Models;
using Microsoft.AspNet.Identity;
using real_estate_agency.Resources;

namespace real_estate_agency.Controllers
{
    [Authorize(Roles = UserStatusDirectory.Roles.ADMINS)]
    public class AdminController : Controller
    {
        AdsManager adManager = new AdsManager();
        PaymentManager payManager = new PaymentManager();
        
        private AppRoleManager RoleManager
        {
            get { return HttpContext.GetOwinContext().GetUserManager<AppRoleManager>(); }
        }

        private AppUserManager UserManager
        {
            get { return HttpContext.GetOwinContext().GetUserManager<AppUserManager>(); }
        }

        // GET: Admin
        public ActionResult AdminPanel()
        {
            AppRole moderRole = RoleManager.FindByName(UserStatusDirectory.Roles.MODERATORS);
            List<string> modersIds = moderRole.Users.Select(u => u.UserId).ToList();
            List<AppUser> moders = UserManager.Users.Where(u => modersIds.Contains(u.Id)).ToList();
            return View(moders);
        }

        [HttpGet]
        public ActionResult CreateModerator()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> CreateModerator(UserRegisterViewModel userInfo)
        {
            if (ModelState.IsValid)
            {
                if (userInfo.ConfirmPassword != userInfo.Password)
                    ModelState.AddModelError("", Resource.PasswordValidator1);
                else
                {
                    AppUser user = new AppUser
                    {
                        UserName = userInfo.Login,
                        Name = userInfo.Name,
                        Email = userInfo.Email,
                        EmailConfirmed = true,
                        LockoutEnabled = false
                    };

                    IdentityResult creationResult = await UserManager.CreateAsync(user, userInfo.Password);
                    IdentityResult roleResult = await UserManager.AddToRoleAsync(user.Id, UserStatusDirectory.Roles.MODERATORS);
                    if (creationResult.Succeeded && roleResult.Succeeded)
                        return RedirectToAction("AdminPanel");
                    else
                    {
                        creationResult.Errors.ToList().ForEach(err => ModelState.AddModelError("", err));
                        roleResult.Errors.ToList().ForEach(err => ModelState.AddModelError("", err));
                    }
                }
            }
            return View(userInfo);
        }

        public async Task<ActionResult> DeleteModerator(string id)
        {
            AppUser moder = await UserManager.FindByIdAsync(id);
            if (moder == null)
                return View("Error", new string[] { Resource.AdminValidator1 });

            //remove moder's marks
            List<Ad> ads = adManager.GetMarkedAdsByUserAthorId(moder.Id).ToList();
            ads.ForEach(ad => adManager.RemoveMark(ad.Id, moder.Id));

            //remove moder's ads
            ads = adManager.GetAdsByUserAthorId(moder.Id).ToList();
            ads.ForEach(ad => adManager.RemoveById(ad.Id));

            IdentityResult result = await UserManager.DeleteAsync(moder);
            if (result.Succeeded)
                return RedirectToAction("AdminPanel");
            else
                return View("Error", result.Errors);
        }
        
        public ActionResult PricesList()
        {
            return PartialView("PricesList", payManager.Prices);
        }

        [HttpPost]
        public ActionResult AddPrice(int days, decimal amount)
        {
            payManager.AddPrice(new Price
            {
                Amount = amount,
                Days = days
            });
            return PartialView("PricesList", payManager.Prices);
        }
        
        public ActionResult DeletePrice(int id)
        {
            payManager.DeletePriceById(id);
            return PartialView("PricesList", payManager.Prices);
        }
    }
}

real-estate-agency/Controllers/AdsController.cs
using Microsoft.AspNet.Identity;
using real_estate_agency.Infrastructure;
using real_estate_agency.Models;
using real_estate_agency.Models.ViewModels;
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Web;

namespace real_estate_agency.Controllers
{
    [Authorize]
    public class AdsController : Controller
    {
        AdsManager adsManager = new AdsManager();
        AdsManager forImages = new AdsManager();

        UserStatusDirectory userStatDirect = new UserStatusDirectory();

        public ActionResult Index()
        {
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Add()
        {
            if (User?.Identity.IsAuthenticated ?? false)
            {
                try
                {
                    UserStatus status = userStatDirect.GetUserStatus(User);
                    if (status.isBlocked)
                        return RedirectToAction("Logout", "Account", new { lockoutTime = status.lockoutTime});
                    if (!string.IsNullOrEmpty(status.NotificationsCountSign))
                        ViewBag.NotifCount = status.NotificationsCountSign;
                }
                catch (Exception ex)
                {
                    return View("Error", new string[] { ex.Message });
                }
            }
            if (Request.UrlReferrer == null)
                // recheck later
                ViewBag.ReturnUrl = "/Home/Index";
            else
                ViewBag.ReturnUrl = Request.UrlReferrer.ToString();
            return View();
        }

        [HttpPost]
        public ActionResult Add(Ad ad, string returnUrl)
        {
            if(Request.Form["g-recaptcha-response"] != string.Empty)
            {
                List<string> phonesList = new List<string>();
                foreach (string field in Request.Form)
                {
                    if (field.Contains("Phone"))
                    {
                        phonesList.Add(Request.Form[field]);
                    }
                }
                ad.Phone = String.Join("|", phonesList);

                ad.PrevImage = Url.Content("~/Content/images/nophoto.png");
                ad.Images = "";

                var upload = Request.Files["uPrevImage"];
                if (upload != null && upload.ContentType.Contains("image/"))
                {
                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(upload.FileName);
                    GoogleDriveManager driveClient = new GoogleDriveManager();
                    string new_image = driveClient.DriveUploadAndGetSrc(upload);
                    ad.PrevImage = Url.Content(new_image);
                }


                List<string> imagesList = new List<string>();
                foreach (string field in Request.Files)
                {
                    if (field.Contains("Images"))
                    {
                        var up = Request.Files[field];
                        if (up != null && up.ContentType.Contains("image/"))
                        {
                            string fileName = Guid.NewGuid().ToString() + Path.GetExtension(up.FileName);
                            GoogleDriveManager driveClient = new GoogleDriveManager();
                            string addr = driveClient.DriveUploadAndGetSrc(up);
                            imagesList.Add(addr);
                        }
                    }
                }
                ad.Images = String.Join("|", imagesList);


                if (UserStatusDirectory.IsPremium(User.Identity.GetUserId(), HttpContext.GetOwinContext()))
                {
                    ad.IsPremium = true;
                }

                adsManager.AddNewAd(ad);
            }
            if (String.IsNullOrEmpty(returnUrl))
            {
                return Redirect("/Home/Index/");
            }
            return Redirect(returnUrl);
        }

        public ActionResult Edit(int? id, string fromDetailsUrl)
        {
            if(id == null)
            {
                return RedirectToAction("Index", "Home");
            }
            if (User?.Identity.IsAuthenticated ?? false)
            {
                try
                {
                    UserStatus status = userStatDirect.GetUserStatus(User);
                    if (status.isBlocked)
                        return RedirectToAction("Logout", "Account", new { lockoutTime = status.lockoutTime });
                    if (!string.IsNullOrEmpty(status.NotificationsCountSign))
                        ViewBag.NotifCount = status.NotificationsCountSign;
                }
                catch (Exception ex)
                {
                    return View("Error", new string[] { ex.Message });
                }
            }

            Ad ad = adsManager.FindById(id);
            string userId = User.Identity.GetUserId();

            if (ad == null)
                return View("Error", new string[] { "Объявление с указанным id не существует!" });
            else if (!UserStatusDirectory.IsOwnerOfAd(User, ad))
                return View("Error", new string[] { "У вас нет прав редактировать это объявление!" });
            else
            {
                if (!string.IsNullOrEmpty(fromDetailsUrl))
                {
                    ViewBag.FromDetailsUrl = fromDetailsUrl;
                    ViewBag.ReturnUrl = null;
                }
                else
                    ViewBag.ReturnUrl = Request.UrlReferrer.ToString();
                return View(ad);
            }
        }

        [HttpPost]
        public ActionResult Edit(Ad ad, string returnUrl, string fromDetailsUrl)
        {
            //Телефоны
            List<string> phonesList = new List<string>();
            foreach (string field in Request.Form)
            {
                if (field.Contains("Phone"))
                {
                    phonesList.Add(Request.Form[field]);
                }
            }
            ad.Phone = String.Join("|", phonesList);

            // Обновить картинку на превью
            var upload = Request.Files["uPrevImage"];
            if (upload != null && upload.ContentType.Contains("image/"))
            {
                string fileName = Guid.NewGuid().ToString() + Path.GetExtension(upload.FileName);
                GoogleDriveManager driveClient = new GoogleDriveManager();
                string path = driveClient.DriveUploadAndGetSrc(upload);
                ad.PrevImage = Url.Content(path);
            }

            ad.Images = "";
            List<string> imagesList = new List<string>();

            //Обработка существующих картинок (если выключен чекбокс - удалить)
            string existingImagesSet = forImages.FindById(ad.Id).Images;
            if (!String.IsNullOrEmpty(existingImagesSet))
            {
                string[] existingImages = existingImagesSet.Split('|');
                foreach (string field in Request.Form)
                {
                    //выбрать все чекбоксы
                    if (field.Contains("remove_check"))
                    {
                        var q = Request.Form[field];
                        int number = Int32.Parse(field.Split('-')[1]);
                        // выбрать выключенные чекбоксы
                        if (q == "false")
                        {
                            //удалить с сервера
                            //System.IO.File.Delete(Server.MapPath());
                            GoogleDriveManager driveClient = new GoogleDriveManager();
                            driveClient.DriveMoveFileToTrash(existingImages[number]);
                        }
                        else
                        {
                            //оставить в списке
                            imagesList.Add(existingImages[number]);
                        }
                    }
                }
            }
            
            //Получаем новые картинки из полей загрузки файлов
            foreach (string field in Request.Files)
            {
                if (field.Contains("Images"))
                {
                    var up = Request.Files[field];
                    if (up != null && up.ContentType.Contains("image/"))
                    {
                        string fileName = Guid.NewGuid().ToString() + Path.GetExtension(up.FileName);
                        GoogleDriveManager driveClient = new GoogleDriveManager();
                        string addr = driveClient.DriveUploadAndGetSrc(up);
                        imagesList.Add(Url.Content(addr));
                    }
                }
            }
            ad.Images = String.Join("|", imagesList);
            
            adsManager.Edit(ad);
            if (!string.IsNullOrEmpty(fromDetailsUrl))
                return RedirectToAction("Details", new { id = ad.Id, fromDetailsUrl = fromDetailsUrl });
            else if (String.IsNullOrEmpty(returnUrl))
            {
                return Redirect("/Home/Index/");
            }
            else
            {
                return Redirect(returnUrl);
            }

        }

        public ActionResult Remove(int id, string returnUrl)
        {
            if (User?.Identity.IsAuthenticated ?? false)
            {
                try
                {
                    UserStatus status = userStatDirect.GetUserStatus(User);
                    if (status.isBlocked)
                        return RedirectToAction("Logout", "Account", new { lockoutTime = status.lockoutTime });
                    if (!string.IsNullOrEmpty(status.NotificationsCountSign))
                        ViewBag.NotifCount = status.NotificationsCountSign;
                }
                catch (Exception ex)
                {
                    return View("Error", new string[] { ex.Message });
                }
            }

            Ad ad = adsManager.FindById(id);

real-estate-agency/Views/Cabinet/BuyPremium.cshtml
@using real_estate_agency.Models
@using real_estate_agency.Resources;
@model IEnumerable<Price>

@{
    ViewBag.Title = "BuyPremium";
    Layout = "~/Views/Shared/header.cshtml";
}

<div class="container-fluid py-3">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <div class="card card-body">
                <h4 class="text-center mb-5">@Resource.BuyPremium</h4>

                <div class="col-md-12 mx-auto">
                    @if (!ViewBag.IsPremium)
                    {
                        foreach (Price price in Model)
                        {
                            <div>
                                <div class="premium-information"><b style="width: 150px; display: inline-block;">@Resource.PremiumDuration:</b> @price.Days @Resource.PremiumOnDays!</div>
                                <div class="premium-quantity"><b style="width: 150px; display: inline-block;">@Resource.PremiumQuantity:</b> @price.Amount грн</div>
                                @using (Html.BeginForm("BuyPremium", "Cabinet", FormMethod.Post))
                                {
                                    <input type="hidden" name="amount" value="@price.Amount" />
                                    <input type="hidden" name="days" value="@price.Days" />
                                    <br />
                                    <button class="premium-button btn btn-primary" type="submit">@Resource.PremiumBuyButton</button>
                                }
                            </div>
                            <hr />
                        }
                    }
                    else
                    {
                        <p style="text-align: center;">@Resource.PremiumWarning!</p>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

real-estate-agency/Views/Cabinet/ChangePassword.cshtml
@using real_estate_agency.Models.ViewModels;
@using real_estate_agency.Resources;
@model ChangePasswordViewModel

<h4 class="text-center mb-5">@Resource.ChangePassword</h4>

<div class="col-md-6 mx-auto">
    @Html.ValidationSummary(false)
    <fieldset>
        @using (Ajax.BeginForm("ChangePassword", "Cabinet", null, new AjaxOptions { UpdateTargetId = "change-password" }))
        {
            if (!string.IsNullOrEmpty(ViewBag.SuccessMessage))
            {
                <div class="success-message">@ViewBag.SuccessMessage</div>
            }
            @Html.HiddenFor(x => x.IdPassword)
            <div class="form-group">
                @Html.PasswordFor(x => x.Password, new { @class = "form-control input-lg", @placeholder = Resource.CurrentPassword })
            </div>
            <div class="form-group">
                @Html.PasswordFor(x => x.NewPassword, new { @class = "form-control input-lg", @placeholder = Resource.NewPassword })
            </div>
            <div class="form-group">
                @Html.PasswordFor(x => x.ConfirmNewPassword, new { @class = "form-control input-lg", @placeholder = Resource.ConfirmNewPassword })
            </div>
            <button class="btn btn-lg btn-primary btn-block" type="submit">@Resource.ChangeButton</button>
        }
    </fieldset>
</div>

real-estate-agency/Views/Cabinet/ChangeProfile.cshtml
@using real_estate_agency.Models.ViewModels;
@using real_estate_agency.Resources;
@model ChangeProfileViewModel

<h4 class="text-center mb-5">@Resource.ProfileSettings</h4>

<div class="col-md-6 mx-auto">
    @Html.ValidationSummary(false)
    <fieldset>
        @using (Ajax.BeginForm("ChangeProfile", "Cabinet", null, new AjaxOptions { UpdateTargetId = "change-profile" }))
        {
            if (!string.IsNullOrEmpty(ViewBag.SuccessMessage))
            {
                <div class="success-message">@ViewBag.SuccessMessage</div>
            }
            @Html.HiddenFor(x => x.IdProfile)
            <div class="form-group">
                @Html.TextBoxFor(x => x.Login, new { @class = "form-control input-lg", @placeholder = Resource.InputLogin })
            </div>
            <div class="form-group">
                @Html.TextBoxFor(x => x.Name, new { @class = "form-control input-lg", @placeholder = Resource.InputName })
            </div>
            <button class="btn btn-lg btn-primary btn-block" type="submit">@Resource.ChangeButton</button>
        }
    </fieldset>
</div>

real-estate-agency/Views/Cabinet/ConfirmPayment.cshtml
@using real_estate_agency.Infrastructure;
@using real_estate_agency.Resources;
@model PaymentData
@{
    ViewBag.Title = "ConfirmPayment";
    Layout = "~/Views/Shared/header.cshtml";
}

<div class="container-fluid py-3">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <div class="card card-body">
                <h4 class="text-center mb-5">@Resource.PaymentForPay</h4>
                <div class="col-md-12 mx-auto">
                    <div><b style="display: inline-block; width: 150px;">@Resource.PaymentNumber:</b> @Model.Payment.Id</div>
                    <div><b style="display: inline-block; width: 150px;">@Resource.PremiumDuration:</b> @Model.Payment.Days @Resource.PremiumOnDays.</div>
                    <div><b style="display: inline-block; width: 150px;">@Resource.PremiumSum:</b> @Model.Payment.Amount грн.</div>
                    <hr />
                    <div class="alert alert-info">@Resource.PremiumWarning2</div>
                    <hr />
                    <form method="POST" action="https://www.liqpay.com/api/3/checkout" accept-charset="utf-8">
                        <input type="hidden" name="data" value="@Model.Data" />
                        <input type="hidden" name="signature" value="@Model.Signature" />
                        <button class="btn btn-primary" type="submit">@Resource.Confirm</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

real-estate-agency/Views/Cabinet/Index.cshtml
@using real_estate_agency.Models;
@using real_estate_agency.Infrastructure;
@using real_estate_agency.Resources;

@model AppUser
@{
    Layout = "~/Views/Shared/header.cshtml";
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <script type="text/javascript">
        function notificationLinkClick() {
            document.getElementById("notif-link").innerHTML = @Resource.Notifications;
            document.getElementById("cabinet-link").innerHTML = @Resource.PersonalCabinet;
        }
    </script>
</head>
<body>
    <div class="container-fluid py-3">
        <div class="row">
            <div class="col-md-12 mx-auto">
                <div class="card card-body">
                    <h3 class="text-center mb-4">@Resource.PersonalCabinet</h3>
                    <div class="nav-container cabinet col-xl-12 mx-auto">
                        <div class="row">
                            <div class="cabinet-item col">
                                @Ajax.ActionLink(Resource.MyAds, "MyAds", "Cabinet", new AjaxOptions() { UpdateTargetId = "contentDisplay" })
                            </div>
                            <div class="cabinet-item col">
                                @Ajax.ActionLink(Resource.MyBookmarks, "MyMarks", "Cabinet", new AjaxOptions() { UpdateTargetId = "contentDisplay" })
                            </div>
                            <div class="cabinet-item col">
                                @Ajax.ActionLink(Resource.MyPayments, "MyPayments", "Cabinet", new AjaxOptions() { UpdateTargetId = "contentDisplay" })
                            </div>
                            <div class="cabinet-item col">
                                @Html.ActionLink(Resource.BuyPremium, "BuyPremium", "Cabinet")
                            </div>
                            <div class="cabinet-item col">
                                @{
                                    string notif = Resource.Notifications + " " + ViewBag.NotifCount;
                                }
                                @Ajax.ActionLink(notif, "MyNotifications", "Cabinet", null, new AjaxOptions() { UpdateTargetId = "contentDisplay" },
                                    new { onclick = "notificationLinkClick()", id = "notif-link" })
                            </div>
                            <div class="cabinet-item col">
                                @Ajax.ActionLink(Resource.Profile, "ProfileSettings", "Cabinet", new AjaxOptions() { UpdateTargetId = "contentDisplay" })
                            </div>
                            @if (UserStatusDirectory.IsAdmin(User))
                            {
                                <div class="cabinet-item col">
                                    @Html.ActionLink(Resource.AdminPanel, "AdminPanel", "Admin")
                                </div>

                            }
                            else if (UserStatusDirectory.IsModerator(User))
                            {
                                <div class="cabinet-item col">
                                    @Html.ActionLink(Resource.ModeratorPanel, "ModeratorPanel", "Moderator");
                                </div>

                            }
                        </div>
                    </div>
                    <div id="contentDisplay">
                        @{Html.RenderAction("MyAds", "Cabinet");}
                    </div>

                </div>
            </div>
        </div>
    </div>
    <script>
        $(function () {
            $(".cabinet-item a").click(function () {
                $(".cabinet-item a").removeClass("active");
                $(this).toggleClass("active");
            })
        });
    </script>
</body>
</html>

real-estate-agency/Views/Cabinet/MyAds.cshtml
@using real_estate_agency.Models;
@using real_estate_agency.Resources;
@using real_estate_agency.Infrastructure;
@using real_estate_agency.Resources;
@model IEnumerable<Ad>

<link rel="stylesheet" href="~/Content/jquery.fancybox.css" />

<h4 class="text-center mb-5">@Resource.MyAds</h4>

<div class="container">
    @if ((Model?.Count() ?? 0) == 0)
    {
        <h2>@Resource.NoAds</h2>
    }
    else
    {
        <div class="block col-md-12">
            <div class="row">
                @foreach (var item in Model)
                {
                    <div class="box col-xl-4 col-md-6 col-sm-12 col-xs-12">
                        @if (UserStatusDirectory.UserCanDeleteAd(User, item))
                        {
                            @Html.ActionLink(" ", "Remove", "Ads",
                                                                      new { id = item.Id },
                                                                      new
                                                                      {
                                                                          @class = "remove",
                                                                          onclick = "return confirm('Действительно удалить?');"
                                                                      })
                        }
                        @if (User.Identity.IsAuthenticated)
                        {
                            if (!UserStatusDirectory.IsOwnerOfAd(User, item))
                            {
                                <div id="marks-@(item.Id)">
                                    @{Html.RenderAction("Marks", "Ads", new { id = item.Id });}
                                </div>
                            }
                            else
                            {
                                @Html.ActionLink(" ", "Edit", "Ads", new { id = item.Id }, new { @class = "edit" })
                            }
                        }
                        <center><p class="type">@item.Type</p></center>
                        <a class="single-item" href="@(item.PrevImage)">
                            <div class="img-box" style="background-image: url(@(item.PrevImage))">
                                <div class="quantity-box">
                                    <strong>@item.Value @item.Currency</strong>
                                </div>
                            </div>
                        </a>

                        <div class="info-box">
                            <a href="/Ads/Details/@item.Id.ToString()">
                                <div class="alert title">@item.Title</div>
                            </a>
                            <p><strong>@Resource.AddEditCategory:</strong> @item.Category</p>
                            <p><strong>@Resource.AddEditAddress:</strong> @item.Address</p>

                            <p>@Html.ActionLink(Resource.Details, "Details", "Ads", new { id = item.Id }, new { @class = "" })</p>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                }
            </div>
        </div>
    }
</div>

<script src="~/Scripts/jquery.fancybox.pack.js"></script>
<script src="~/Scripts/gallery-single.js"></script>

real-estate-agency/Views/Cabinet/MyMarks.cshtml
@using real_estate_agency.Models;
@using real_estate_agency.Infrastructure;
@using real_estate_agency.Resources;
@model IEnumerable<Ad>

<link rel="stylesheet" href="~/Content/jquery.fancybox.css" />

<h4 class="text-center mb-5">@Resource.MyBookmarks</h4>

<div class="container">
    @if ((Model?.Count() ?? 0) == 0)
    {
        <h2>@Resource.NoBookmarks</h2>
    }
    else
    {
        <div class="block col-md-12">
            <div class="row">
                @foreach (var item in Model)
                {
                    <div class="box col-xl-4 col-md-6 col-sm-12 col-xs-12">
                        @if (UserStatusDirectory.UserCanDeleteAd(User, item))
                        {
                            @Html.ActionLink(" ", "Remove", "Ads",
                                                                    new { id = item.Id },
                                                                    new
                                                                    {
                                                                        @class = "remove",
                                                                        onclick = "return confirm('Действительно удалить?');"
                                                                    })
                        }
                        @if (User.Identity.IsAuthenticated)
                        {
                            if (!UserStatusDirectory.IsOwnerOfAd(User, item))
                            {
                                <div id="marks-@(item.Id)">
                                    @{Html.RenderAction("Marks", "Ads", new { id = item.Id });}
                                </div>
                            }
                            else
                            {
                                @Html.ActionLink(" ", "Edit", "Ads", new { id = item.Id }, new { @class = "edit" })
                            }
                        }
                        <center><p class="type">@item.Type</p></center>
                        <a class="single-item" href="@(item.PrevImage)">
                            <div class="img-box" style="background-image: url(@(item.PrevImage))">
                                <div class="quantity-box">
                                    <strong>@item.Value @item.Currency</strong>
                                </div>
                            </div>
                        </a>

                        <div class="info-box">
                            <a href="/Ads/Details/@item.Id.ToString()">
                                <div class="alert title">@item.Title</div>
                            </a>
                            <p><strong>@Resource.AddEditCategory:</strong> @item.Category</p>
                            <p><strong>@Resource.AddEditAddress:</strong> @item.Address</p>

                            <p>@Html.ActionLink(Resource.Details, "Details", "Ads", new { id = item.Id }, new { @class = "" })</p>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                }
            </div>
        </div>
    }
</div>

<script src="~/Scripts/jquery.fancybox.pack.js"></script>
<script src="~/Scripts/gallery-single.js"></script>

real-estate-agency/Views/Cabinet/MyPayments.cshtml
@using real_estate_agency.Models;
@using real_estate_agency.Resources;
@model IEnumerable<Payment>

<h4 class="text-center mb-5">@Resource.MyPayments</h4>

<div class="col-md-6 mx-auto">
    @if ((Model?.Count() ?? 0) == 0)
    {
        <p style="text-align: center;">@Resource.NoPayments</p>
    }
    else
    {
        foreach (Payment payment in Model)
        {
            <div>
                <div class="payment-date">@payment.Date</div>
                <div class="peyment-days">@Resource.SubDuration: @payment.Days</div>
                @if (payment.ConfirmedDate != null)
                {
                    <div class="payment-confirmation">@payment.ConfirmedDate - @Resource.PaymentConfirmed.</div>
                }
                else
                {
                    <div class="payment-confirmation">@Resource.PaymentNotConfirmed.</div>
                }
            </div>
            <hr />
        }
    }
</div>