real-estate-agency/Controllers/AdminController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using real_estate_agency.Infrastructure;
using Microsoft.AspNet.Identity.Owin;
using real_estate_agency.Models.ViewModels;
using System.Threading.Tasks;
using real_estate_agency.Models;
using Microsoft.AspNet.Identity;
using real_estate_agency.Resources;

namespace real_estate_agency.Controllers
{
    [Authorize(Roles = UserStatusDirectory.Roles.ADMINS)]
    public class AdminController : Controller
    {
        AdsManager adManager = new AdsManager();
        PaymentManager payManager = new PaymentManager();
        
        private AppRoleManager RoleManager
        {
            get { return HttpContext.GetOwinContext().GetUserManager<AppRoleManager>(); }
        }

        private AppUserManager UserManager
        {
            get { return HttpContext.GetOwinContext().GetUserManager<AppUserManager>(); }
        }

        // GET: Admin
        public ActionResult AdminPanel()
        {
            AppRole moderRole = RoleManager.FindByName(UserStatusDirectory.Roles.MODERATORS);
            List<string> modersIds = moderRole.Users.Select(u => u.UserId).ToList();
            List<AppUser> moders = UserManager.Users.Where(u => modersIds.Contains(u.Id)).ToList();
            return View(moders);
        }

        [HttpGet]
        public ActionResult CreateModerator()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> CreateModerator(UserRegisterViewModel userInfo)
        {
            if (ModelState.IsValid)
            {
                if (userInfo.ConfirmPassword != userInfo.Password)
                    ModelState.AddModelError("", Resource.PasswordValidator1);
                else
                {
                    AppUser user = new AppUser
                    {
                        UserName = userInfo.Login,
                        Name = userInfo.Name,
                        Email = userInfo.Email,
                        EmailConfirmed = true,
                        LockoutEnabled = false
                    };

                    IdentityResult creationResult = await UserManager.CreateAsync(user, userInfo.Password);
                    IdentityResult roleResult = await UserManager.AddToRoleAsync(user.Id, UserStatusDirectory.Roles.MODERATORS);
                    if (creationResult.Succeeded && roleResult.Succeeded)
                        return RedirectToAction("AdminPanel");
                    else
                    {
                        creationResult.Errors.ToList().ForEach(err => ModelState.AddModelError("", err));
                        roleResult.Errors.ToList().ForEach(err => ModelState.AddModelError("", err));
                    }
                }
            }
            return View(userInfo);
        }

        public async Task<ActionResult> DeleteModerator(string id)
        {
            AppUser moder = await UserManager.FindByIdAsync(id);
            if (moder == null)
                return View("Error", new string[] { Resource.AdminValidator1 });

            //remove moder's marks
            List<Ad> ads = adManager.GetMarkedAdsByUserAthorId(moder.Id).ToList();
            ads.ForEach(ad => adManager.RemoveMark(ad.Id, moder.Id));

            //remove moder's ads
            ads = adManager.GetAdsByUserAthorId(moder.Id).ToList();
            ads.ForEach(ad => adManager.RemoveById(ad.Id));

            IdentityResult result = await UserManager.DeleteAsync(moder);
            if (result.Succeeded)
                return RedirectToAction("AdminPanel");
            else
                return View("Error", result.Errors);
        }
        
        public ActionResult PricesList()
        {
            return PartialView("PricesList", payManager.Prices);
        }

        [HttpPost]
        public ActionResult AddPrice(int days, decimal amount)
        {
            payManager.AddPrice(new Price
            {
                Amount = amount,
                Days = days
            });
            return PartialView("PricesList", payManager.Prices);
        }
        
        public ActionResult DeletePrice(int id)
        {
            payManager.DeletePriceById(id);
            return PartialView("PricesList", payManager.Prices);
        }
    }
}

real-estate-agency/Controllers/ModeratorController.cs
using System;
using System.Web;
using System.Web.Mvc;
using real_estate_agency.Infrastructure;
using System.Threading.Tasks;
using real_estate_agency.Models;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity;
using real_estate_agency.Models.ViewModels;
using real_estate_agency.Resources;

namespace real_estate_agency.Controllers
{
    [Authorize(Roles = UserStatusDirectory.Roles.ADMINS + "," + UserStatusDirectory.Roles.MODERATORS)]
    public class ModeratorController : Controller
    {
        AdsManager adsManager = new AdsManager();

        private AppRoleManager RoleManager
        {
            get { return HttpContext.GetOwinContext().GetUserManager<AppRoleManager>(); }
        }

        private AppUserManager UserManager
        {
            get { return HttpContext.GetOwinContext().GetUserManager<AppUserManager>(); }
        }

        [Authorize(Roles = UserStatusDirectory.Roles.MODERATORS)]
        public ActionResult ModeratorPanel()
        {
            return View();
        }

        [HttpGet]
        public ActionResult RemoveAd(int adId, string returnUrl)
        {
            RemoveAdViewModel model = new RemoveAdViewModel
            {
                ReturnURL = returnUrl,
                AdId = adId
            };
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> RemoveAd(RemoveAdViewModel model)
        {
            Ad deletedAd = adsManager.FindById(model.AdId);
            AppUser user = await UserManager.FindByIdAsync(deletedAd.UserAuthorId);
            AppUser sender = await UserManager.FindByIdAsync(User.Identity.GetUserId());

            string text = $"Ваше объявление {deletedAd.Title} было удалено. " +
                $"Причина: {model.Message}";

            Notifier notifier = new Notifier();
            IdentityResult result = notifier.NotifyUser(user, text, sender);

            if (result.Succeeded)
            {
                adsManager.RemoveById(deletedAd.Id);
                return Redirect(model.ReturnURL);
            }
            else
                return View("Error", result.Errors);
        }

        [HttpGet]
        public PartialViewResult SearchUserPanel()
        {
            SearchUserFilter filter = new SearchUserFilter(UserManager, RoleManager);
            SearchUserViewModel model = new SearchUserViewModel();
            model.ResultUsers = filter.SearchUsers(model);
            return PartialView(model);
        }

        [HttpPost]
        public PartialViewResult SearchUser(SearchUserViewModel model)
        {
            SearchUserFilter filter = new SearchUserFilter(UserManager, RoleManager);
            model.ResultUsers = filter.SearchUsers(model);
            return PartialView("SearchUserPanel", model);
        }

        [HttpGet]
        public ActionResult BlockUser(string id)
        {
            BlockUserViewModel model = new BlockUserViewModel
            {
                UserId = id
            };
            ViewBag.ReturnUrl = Request.UrlReferrer.ToString();
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> BlockUser(BlockUserViewModel model, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                AppUser user = UserManager.FindById(model.UserId);
                if (user == null)
                    return View("Error", new string[] { Resource.ModeratorValidator1 });

                TimeSpan duration = TimeSpan.FromDays(0);
                switch (model.Duration)
                {
                    case BlockDuration.Hour:
                        duration = TimeSpan.FromHours(1);
                        break;
                    case BlockDuration.Day:
                        duration = TimeSpan.FromDays(1);
                        break;
                    case BlockDuration.Week:
                        duration = TimeSpan.FromDays(7);
                        break;
                    case BlockDuration.Month:
                        duration = TimeSpan.FromDays(30);
                        break;
                    case BlockDuration.Forever:
                        duration = TimeSpan.FromDays(365 * 100);
                        break;
                }
                user.LockoutEndDateUtc = DateTime.UtcNow + duration;

                IdentityResult result = await UserManager.UpdateAsync(user);
                if (result.Succeeded)
                {
                    AppUser sender = await UserManager.FindByIdAsync(User.Identity.GetUserId());
                    Email.EmailSender.SendUserBlockedMail(user, model.Duration, model.Message, sender);
                    return Redirect(returnUrl);
                }
                else
                    return View("Error", result.Errors);
            }

            return View(model);
        }

        public async Task<ActionResult> DeblockUser(string id)
        {
            AppUser user = await UserManager.FindByIdAsync(id);
            if (user == null)
                return View("Error", new string[] { Resource.ModeratorValidator1 });

            user.LockoutEndDateUtc = null;
            IdentityResult result = await UserManager.UpdateAsync(user);
            if (result.Succeeded)
                return Redirect(Request.UrlReferrer.ToString());
            else
                return View("Error", result.Errors);
        }
    }
}

real-estate-agency/Views/Admin/AdminPanel.cshtml
@using real_estate_agency.Models;
@using real_estate_agency.Resources;
@model IEnumerable<AppUser>
@{
    Layout = "~/Views/Shared/header.cshtml";
}

<div class="container-fluid py-3">
    <div class="row">
        <div class="col-md-12 mx-auto">
            <div class="card card-body">
                <h3 class="text-center mb-4">@Resource.AdminPanel</h3>
                <!--Prices-->
                <div class="mx-auto">
                    <h4 class="text-center mb-5">@Resource.AddPremium</h4>
                    @using (Ajax.BeginForm("AddPrice", "Admin", null, new AjaxOptions { UpdateTargetId = "prices-list" }))
                    {
                        <div class="form-group">
                            <label for="adminpanel-days">@Resource.PremiumDaysCount:</label>
                            <input class="form-control" style="max-width: 300px;" id="adminpanel-days" name="days" type="text" />
                        </div>
                        <div class="form-group">
                            <label for="adminpanel-amount">@Resource.PremiumQuantity:</label>
                            <input class="form-control" style="max-width: 300px;" id="adminpanel-amount" name="amount" type="text" />
                        </div>
                        <button class="btn btn-primary" type="submit">@Resource.AddQuantity</button>
                    }
                    <br />
                    <div id="prices-list">
                        @{ Html.RenderAction("PricesList", "Admin"); }
                    </div>
                </div>
                <fieldset>
                    <h4 class="text-center mb-5">@Resource.Moderators</h4>
                    <table class="table table-responsive-sm">
                        <thead>
                            <tr>
                                <th>@Resource.Name</th>
                                <th>@Resource.Login</th>
                                <th>Email</th>
                                <th>@Html.ActionLink(Resource.AddModerator, "CreateModerator")</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (AppUser moder in Model)
                            {
                                <tr>
                                    <td>@moder.Name</td>
                                    <td>@moder.UserName</td>
                                    <td>@moder.Email</td>
                                    <td>@Html.ActionLink(@Resource.Delete, "DeleteModerator", new { id = moder.Id })</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                    <br /><br /><br />
                    <h4 class="text-center mb-5">@Resource.Users</h4>
                    <div id="search-user-panel">
                        @{ Html.RenderAction("SearchUserPanel", "Moderator"); }
                    </div>
                </fieldset>
            </div>
        </div>
    </div>
</div>

real-estate-agency/Views/Admin/CreateModerator.cshtml
@using real_estate_agency.Models.ViewModels;
@using real_estate_agency.Resources;
@model UserRegisterViewModel

@{
    Layout = "~/Views/Shared/header.cshtml";
}

<div class="container-fluid py-3">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <div class="card card-body">
                <h3 class="text-center mb-4">@Resource.AddModerator</h3>
                @Html.ValidationSummary(false)
                <fieldset>
                    @using (Html.BeginForm("CreateModerator", "Admin", FormMethod.Post))
                    {
                        <div class="form-group">
                            @Html.TextBoxFor(x => x.Login, new { @class = "form-control input-lg", placeholder = Resource.InputLogin })
                        </div>
                        <div class="form-group">
                            @Html.TextBoxFor(x => x.Name, new { @class = "form-control input-lg", placeholder = Resource.InputName })
                        </div>
                        <div class="form-group">
                            @Html.TextBoxFor(x => x.Email, new { @class = "form-control input-lg", placeholder = Resource.InputEmail })
                        </div>
                        <div class="form-group">
                            @Html.PasswordFor(x => x.Password, new { @class = "form-control input-lg", placeholder = Resource.InputPassword })
                        </div>
                        <div class="form-group">
                            @Html.PasswordFor(x => x.ConfirmPassword, new { @class = "form-control input-lg", placeholder = Resource.ConfirmPassword })
                        </div>
                        <input class="btn btn-lg btn-primary btn-block" value=@Resource.AddButton type="submit">
                    }
                </fieldset>
            </div>
        </div>
    </div>
</div>

real-estate-agency/Views/Admin/PricesList.cshtml
@using real_estate_agency.Models;
@using real_estate_agency.Resources;
@model IEnumerable<Price>

<h4 class="text-center mb-5">@Resource.PremiumCostTable</h4>
<table class="table table-responsive-sm">
    <thead>
        <tr>
            <th>@Resource.PremiumDaysCount</th>
            <th>@Resource.PremiumQuantity</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Price price in Model)
        {
            <tr>
                <td>@price.Days</td>
                <td>@price.Amount грн</td>
                <td>@Ajax.ActionLink(Resource.Delete, "DeletePrice", "Admin", new { id = price.Id }, new AjaxOptions { UpdateTargetId = "prices-list" })</td>
            </tr>
        }
    </tbody>
</table>